  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/kalpashram?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: root

    mail:
      host: smtp.gmail.com
      port: 587
      username: varsharitu55@gmail.com
      password: bjur morn jqjh xfbj
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update       # options: validate | update | create | create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
